/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import assets.Item;
import assets.NumberFormat;
import controller.CategoriaProdutoDAO;
import controller.MarcaProdutoDAO;
import controller.ProdutoDAO;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Produto;
import model.JNumberFormatField;

/**
 *
 */
public class CadastroProduto extends javax.swing.JFrame {
        
    
         String op = "";
         int idC = 0;
    /**
     * Creates new form CadastroProduto
     */
    public CadastroProduto() throws SQLException {
        
        initComponents();
         
        this.getLastId();
        
   // Bloqueia o Resize: //
        this.setResizable(false); 
        
    /* Maximiza a janela ao iniciar: //
         this.setExtendedState(jfTelaPrincipal.MAXIMIZED_BOTH); */
                
      Color backgroundColor = new Color(206, 222, 255);
        // Alterar a cor do formulário: //
       this.getContentPane().setBackground(backgroundColor);
       
       this.populateMarca();
       this.populateCategoria();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jlCod = new javax.swing.JLabel();
        jtIdProduto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtDiscriminacao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlEAN = new javax.swing.JLabel();
        jtCodEan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jbSalvar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        comboCategoria = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        comboMarca = new javax.swing.JComboBox();
        jtValorCusto = new javax.swing.JTextField();
        jtValorUN = new javax.swing.JTextField();
        jtMargemLucro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Produtos");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barcode.png"))); // NOI18N
        jLabel1.setText("Cadastro de Produtos");

        jlCod.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlCod.setText("Código:");

        jtIdProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtIdProduto.setEnabled(false);
        jtIdProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtIdProdutoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Discriminação:");

        jtDiscriminacao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Custo:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Margem Lucro:");

        jlEAN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlEAN.setText("Código EAN:");

        jtCodEan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtCodEan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCodEanActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Valor UN:");

        jbSalvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gnome_media_floppy.png"))); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/erase.png"))); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Categoria:");

        comboCategoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCategoriaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Marca:");

        comboMarca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMarcaActionPerformed(evt);
            }
        });

        jtValorCusto = new JNumberFormatField();
        jtValorCusto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jtValorUN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtValorUN.setEnabled(false);
        jtValorUN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtValorUNActionPerformed(evt);
            }
        });
        jtValorUN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtValorUNKeyReleased(evt);
            }
        });

        jtMargemLucro = new JNumberFormatField();
        jtMargemLucro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtMargemLucroKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCod)
                            .addComponent(jtIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtValorCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtMargemLucro))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jtValorUN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbSalvar)
                                        .addGap(56, 56, 56)
                                        .addComponent(jbCancelar))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlEAN)
                                            .addComponent(jtCodEan, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jtDiscriminacao, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(22, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlCod)
                            .addComponent(jlEAN)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtCodEan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jtDiscriminacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtValorCusto)
                            .addComponent(jtMargemLucro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(comboMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtValorUN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalvar)
                    .addComponent(jbCancelar))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-807)/2, (screenSize.height-332)/2, 807, 332);
    }// </editor-fold>//GEN-END:initComponents

    private void jtIdProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtIdProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtIdProdutoActionPerformed

    private void jtCodEanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCodEanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCodEanActionPerformed

    private void comboMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMarcaActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        NumberFormat n = new NumberFormat();
        Item selected_categoria = (Item) comboCategoria.getSelectedItem();
        Item selected_marca = (Item) comboMarca.getSelectedItem();
        
        String valor_custo = jtValorCusto.getText();
       /* valor_custo = valor_custo.replace(".", "").replace(",", ".");*/
        
        String margem_lucro = jtMargemLucro.getText();
       /*  margem_lucro = margem_lucro.replace(".", "").replace(",", ".");*/
     
        ProdutoDAO produtoDao = new ProdutoDAO();
        
        if(this.op.equals("editar")){
            Produto p = new Produto(
                Integer.parseInt(jtIdProduto.getText()), 
                jtCodEan.getText(), 
                jtDiscriminacao.getText(), 
                n.commaToPoint(valor_custo), 
                n.commaToPoint(margem_lucro),
                selected_marca.getId(),
                selected_marca.getId()
            );
            
            produtoDao.alterarProduto(p);
        }
        /*else{
            
            Produto p = new Produto(
                0, 
                jtCodEan.getText(), 
                jtDiscriminacao.getText(), 
                n.commaToPoint(valor_custo), 
                n.commaToPoint(margem_lucro),
                selected_marca.getId(),
                selected_marca.getId()
            );

            produtoDao.inserirProduto(p);
            CadastroProduto.this.dispose();
        }*/
        
        /* 
        Validação do formulário PRODUTOS:
        Se houver campos vazios, exibe mensagem de erro solicitando preenchimento*/
        
        if ( (jtCodEan.getText().trim().isEmpty()) && (jtDiscriminacao.getText().trim().isEmpty()) &&  
           (jtValorCusto.getText().trim().isEmpty()) && (jtMargemLucro.getText().trim().isEmpty()) ) {
            JOptionPane.showMessageDialog(null, "É necessário o preenchimento de todos os campos para efetuar o cadastro! Por favor preencha todos os dados!");
        } else {
        Produto p = new Produto(
                0, 
                jtCodEan.getText(), 
                jtDiscriminacao.getText(), 
                n.commaToPoint(valor_custo), 
                n.commaToPoint(margem_lucro),
                selected_marca.getId(),
                selected_marca.getId()
            );
	produtoDao.inserirProduto(p);
        CadastroProduto.this.dispose();
        }
        
       


    }//GEN-LAST:event_jbSalvarActionPerformed

    private void comboCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCategoriaActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        // TODO add your handling code here:
        
// Exibe mensagem de confirmação de cancelamento //
  Object[] options = { "Sim", "Não" };
		int i = JOptionPane.showOptionDialog(null,
				"Deseja realmente cancelar o cadastro? Você perderá todos os dados!", "AVISO:",
				JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE, null,
				options, options[0]);
		if (i == JOptionPane.YES_OPTION) {
			this.dispose();
		}
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jtMargemLucroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtMargemLucroKeyReleased
        // TODO add your handling code here:
        
        NumberFormat n = new NumberFormat();
      
        Float margem_lucro = n.commaToPoint(jtMargemLucro.getText());
        Float valor_custo = n.commaToPoint(jtValorCusto.getText());
        Float divisao = margem_lucro / 100;

        Float valor_unitario = (valor_custo + (valor_custo * divisao));
        
        
        jtValorUN.setText(n.pointToComma(valor_unitario));
       
       
    }//GEN-LAST:event_jtMargemLucroKeyReleased

    private void jtValorUNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtValorUNKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtValorUNKeyReleased

    private void jtValorUNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtValorUNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtValorUNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CadastroProduto().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(CadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox comboCategoria;
    public javax.swing.JComboBox comboMarca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JLabel jlCod;
    private javax.swing.JLabel jlEAN;
    public javax.swing.JTextField jtCodEan;
    public javax.swing.JTextField jtDiscriminacao;
    public javax.swing.JTextField jtIdProduto;
    public javax.swing.JTextField jtMargemLucro;
    public javax.swing.JTextField jtValorCusto;
    public javax.swing.JTextField jtValorUN;
    // End of variables declaration//GEN-END:variables

/*
       public void habilitarCampos(){
    jtCodCat.setEnabled(true);
    jtNomeCat.setEnabled(true);
    jbSalvar.setEnabled(true);
    jbInserir.setEnabled(false);


} 

public void desabilitarCampos(){
        
    jtCodCat.setEnabled(false);
    jtNomeCat.setEnabled(false);
    jbSalvar.setEnabled(false);
    jbInserir.setEnabled(true);
    
    
    
}
    */
    
    public void populateMarca() throws SQLException{
       MarcaProdutoDAO marca = new MarcaProdutoDAO();
       ResultSet rs = marca.toComboBox();
       
        while(rs.next()){                   
            comboMarca.addItem(new Item(rs.getInt("id_marca"), rs.getString("descricao")));
        }
    }
    
    
    public void populateCategoria() throws SQLException{
       CategoriaProdutoDAO cat = new CategoriaProdutoDAO();
       ResultSet rs = cat.toComboBox();
       
        while(rs.next()){                   
            comboCategoria.addItem(new Item(rs.getInt("id_categoria"), rs.getString("descricao")));
        }
    }
    
        public void getLastId(){
        ProdutoDAO produto = new ProdutoDAO();
        int rs = produto.getLastId();
        rs = rs + 1;
 
                
        jtIdProduto.setText(Integer.toString(rs));
    
    }
   
}
