/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import assets.Item;
import controller.ClienteDAO;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.awt.event.ActionListener;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Cliente;
import model.EnderecoCliente;
import model.EnderecoPessoa;
import model.Pessoa;


/**
 *
 * @author danir
 */
public class CadastroCliente extends javax.swing.JFrame {

    /**
     * Creates new form CadastroCliente
     */
    public CadastroCliente() throws SQLException {
        initComponents();
        
        this.getLastId();
        this.populateUF();
        this.populateUF2();
        this.populateCidade(1);
        this.populateCidade2(1);
        
        
    // Bloqueia o Resize: //
        this.setResizable(false); 
        
    /* Maximiza a janela ao iniciar: //
         this.setExtendedState(jfTelaPrincipal.MAXIMIZED_BOTH); */
                
      Color backgroundColor = new Color(206, 222, 255);
        // Alterar a cor do formulário: //
       this.getContentPane().setBackground(backgroundColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitulo = new javax.swing.JLabel();
        jlCodCliente = new javax.swing.JLabel();
        jtCodCliente = new javax.swing.JTextField();
        jlNome = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jltipo = new javax.swing.JLabel();
        jlEmail = new javax.swing.JLabel();
        jtEmail = new javax.swing.JTextField();
        jlDataNasc = new javax.swing.JLabel();
        jtDataNasc = new javax.swing.JFormattedTextField();
        jlTel = new javax.swing.JLabel();
        jtTel = new javax.swing.JFormattedTextField();
        jlCel = new javax.swing.JLabel();
        jtCel = new javax.swing.JFormattedTextField();
        jbSalvar = new javax.swing.JButton();
        tipo_cliente = new javax.swing.JComboBox<>();
        jlCPF = new javax.swing.JLabel();
        jtCpfCnpj = new javax.swing.JFormattedTextField();
        jlRua = new javax.swing.JLabel();
        jtRua = new javax.swing.JTextField();
        jtNro = new javax.swing.JTextField();
        jlNro = new javax.swing.JLabel();
        jlBairro = new javax.swing.JLabel();
        jtBairro = new javax.swing.JTextField();
        jlUF = new javax.swing.JLabel();
        jtUF = new javax.swing.JComboBox();
        jlCidade = new javax.swing.JLabel();
        jtCidade = new javax.swing.JComboBox();
        jlCEP = new javax.swing.JLabel();
        jtCep = new javax.swing.JFormattedTextField();
        jlEndCobranca = new javax.swing.JLabel();
        jlRua1 = new javax.swing.JLabel();
        jtRuaCliente = new javax.swing.JTextField();
        jtNroCliente = new javax.swing.JTextField();
        jlNro1 = new javax.swing.JLabel();
        jlBairro1 = new javax.swing.JLabel();
        jtBairroCliente = new javax.swing.JTextField();
        jlCEP1 = new javax.swing.JLabel();
        jtCepCliente = new javax.swing.JFormattedTextField();
        jtCidadeCliente = new javax.swing.JComboBox();
        jlCidade1 = new javax.swing.JLabel();
        jlUF1 = new javax.swing.JLabel();
        jtUFCliente = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObs = new javax.swing.JTextArea();
        jlNro2 = new javax.swing.JLabel();
        jtRgIe = new javax.swing.JTextField();
        jlObs = new javax.swing.JLabel();
        jbCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Clientes");

        jlTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/group-profile-users.png"))); // NOI18N
        jlTitulo.setText("Cadastro de Clientes");

        jlCodCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlCodCliente.setText("Código:");

        jtCodCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtCodCliente.setEnabled(false);

        jlNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlNome.setText("Nome:");

        jtNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jltipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jltipo.setText("Tipo:");

        jlEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlEmail.setText("E-mail:");

        jtEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jlDataNasc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlDataNasc.setText("Data Nasc:");

        try {
            jtDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtDataNasc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtDataNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtDataNascActionPerformed(evt);
            }
        });

        jlTel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlTel.setText("Tel.:");

        try {
            jtTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtTel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtTelActionPerformed(evt);
            }
        });

        jlCel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlCel.setText("Cel.:");

        try {
            jtCel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#-####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtCel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtCel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCelActionPerformed(evt);
            }
        });

        jbSalvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gnome_media_floppy.png"))); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        tipo_cliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tipo_cliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Física", "Jurídica" }));

        jlCPF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlCPF.setText("CPF:");

        try {
            jtCpfCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtCpfCnpj.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jlRua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlRua.setText("Rua:");

        jtRua.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtRuaActionPerformed(evt);
            }
        });

        jtNro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtNro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNroActionPerformed(evt);
            }
        });

        jlNro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlNro.setText("Nº:");

        jlBairro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlBairro.setText(" Bairro:");

        jtBairro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtBairroActionPerformed(evt);
            }
        });

        jlUF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlUF.setText("UF:");

        jtUF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtUFActionPerformed(evt);
            }
        });

        jlCidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlCidade.setText("Cidade:");

        jtCidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jlCEP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlCEP.setText("CEP:");

        try {
            jtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCepActionPerformed(evt);
            }
        });

        jlEndCobranca.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlEndCobranca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/envelope.png"))); // NOI18N
        jlEndCobranca.setText("Endereço Cobrança");

        jlRua1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlRua1.setText("Rua:");

        jtRuaCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtRuaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtRuaClienteActionPerformed(evt);
            }
        });

        jtNroCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtNroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNroClienteActionPerformed(evt);
            }
        });

        jlNro1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlNro1.setText("Nº:");

        jlBairro1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlBairro1.setText(" Bairro:");

        jtBairroCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtBairroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtBairroClienteActionPerformed(evt);
            }
        });

        jlCEP1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlCEP1.setText("CEP:");

        try {
            jtCepCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtCepCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCepClienteActionPerformed(evt);
            }
        });

        jtCidadeCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jlCidade1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlCidade1.setText("Cidade:");

        jlUF1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlUF1.setText("UF:");

        jtUFCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtUFCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtUFClienteActionPerformed(evt);
            }
        });

        txtObs.setColumns(20);
        txtObs.setRows(5);
        jScrollPane1.setViewportView(txtObs);

        jlNro2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlNro2.setText("RG");

        jtRgIe.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtRgIe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtRgIeActionPerformed(evt);
            }
        });

        jlObs.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlObs.setText("Observações:");

        jbCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/erase.png"))); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(jlTitulo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbSalvar)
                .addGap(39, 39, 39)
                .addComponent(jbCancelar)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlCodCliente))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlNome)
                                        .addGap(302, 302, 302)
                                        .addComponent(jltipo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tipo_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jlEmail))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlDataNasc)
                                    .addComponent(jtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlObs)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 926, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(338, 338, 338)
                                        .addComponent(jlEndCobranca))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlCPF))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlNro2)
                                            .addComponent(jtRgIe, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlTel))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtCel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlCel))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlRua)
                                            .addComponent(jtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(14, 14, 14)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlNro)
                                            .addComponent(jtNro, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlCEP))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlBairro)
                                    .addComponent(jtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlUF)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtUF, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlCidade))))
                                .addGap(14, 14, 14)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtRuaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlRua1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNro1)
                            .addComponent(jtNroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlBairro1)
                            .addComponent(jtBairroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCEP1)
                            .addComponent(jtCepCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlUF1)
                            .addComponent(jtUFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtCidadeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlCidade1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlTitulo)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlEmail)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jlCodCliente)
                                            .addComponent(jlNome)
                                            .addComponent(jltipo))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jtCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tipo_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlDataNasc)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(4, 4, 4)
                                            .addComponent(jlNro)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jtNro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jlNro2)
                                                .addComponent(jlCPF))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtRgIe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jlCel)
                                            .addComponent(jlRua))
                                        .addGap(29, 29, 29))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlTel)
                                        .addGap(31, 31, 31))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jtCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jlBairro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jlCEP)
                                        .addGap(31, 31, 31))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jlCidade)
                                .addGap(8, 8, 8)
                                .addComponent(jtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlUF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addComponent(jlEndCobranca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlRua1)
                    .addComponent(jlNro1)
                    .addComponent(jlBairro1)
                    .addComponent(jlCEP1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtRuaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtNroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtBairroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCepCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlUF1)
                    .addComponent(jlCidade1))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCidadeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtUFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jlObs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalvar)
                    .addComponent(jbCancelar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(985, 743));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtDataNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtDataNascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtDataNascActionPerformed

    private void jtCelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCelActionPerformed

    private void jtTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtTelActionPerformed

    private void jtRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtRuaActionPerformed

    private void jtNroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNroActionPerformed

    private void jtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtBairroActionPerformed

    private void jtCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCepActionPerformed

    private void jtUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtUFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtUFActionPerformed

    private void jtRuaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtRuaClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtRuaClienteActionPerformed

    private void jtNroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNroClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNroClienteActionPerformed

    private void jtBairroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtBairroClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtBairroClienteActionPerformed

    private void jtCepClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCepClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCepClienteActionPerformed

    private void jtUFClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtUFClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtUFClienteActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
       
       String[] data_part = jtDataNasc.getText().split("/");
       
       String data_nasc = data_part[2] + "-" + data_part[1] + "-" + data_part[0];
       
       DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
       Date date = new Date();
       
         
       Cliente cli = new Cliente(0, tipo_cliente.getSelectedItem().toString(), data_nasc, txtObs.getText(), 0);
       Pessoa pes = new Pessoa(0, jtNome.getText(), jtRgIe.getText(), jtCpfCnpj.getText(), jtEmail.getText(), jtTel.getText(), jtCel.getText(),  dateFormat.format(date));
       EnderecoPessoa endereco_pessoa = new EnderecoPessoa(0, jtRua.getText(), Integer.parseInt(jtNro.getText()), jtCep.getText(), jtBairro.getText(), jtCidade.getSelectedItem().toString(), jtUF.getSelectedItem().toString(), 0);
       EnderecoCliente endereco_cliente = new EnderecoCliente(0, jtRuaCliente.getText(), Integer.parseInt(jtNroCliente.getText()), jtCepCliente.getText(), jtBairroCliente.getText(), jtCidadeCliente.getSelectedItem().toString(), jtUFCliente.getSelectedItem().toString(), 0);
       
       ClienteDAO clienteDao = new ClienteDAO();

       // Validação do formulário CLIENTE
       //Se houver campos vazios, exibe mensagem de erro solicitando preenchimento
        if ( (jtNome.getText().trim().isEmpty()) && (jtEmail.getText().trim().isEmpty()) && 
                (jtDataNasc.getText().trim().isEmpty()) && 
                (jtCpfCnpj.getText().trim().isEmpty()) && (jtRgIe.getText().trim().isEmpty()) && 
                (jtTel.getText().trim().isEmpty())&& (jtCel.getText().trim().isEmpty()) && 
                (jtRua.getText().trim().isEmpty()) && (jtNro.getText().trim().isEmpty()) && 
                (jtBairro.getText().trim().isEmpty()) && (jtCep.getText().trim().isEmpty()) && 
                (jtRuaCliente.getText().trim().isEmpty()) && (jtNroCliente.getText().trim().isEmpty()) && 
                (jtBairroCliente.getText().trim().isEmpty()) && (jtCepCliente.getText().trim().isEmpty()) ) {
            JOptionPane.showMessageDialog(null, "É necessário o preenchimento de todos os campos para efetuar o cadastro! Por favor preencha todos os dados!");
        } else {
	clienteDao.inserirCliente(pes, endereco_pessoa, cli, endereco_cliente);
        CadastroCliente.this.dispose();
        }
              
       jfConsultaCliente jfConsulta = new jfConsultaCliente();
       jfConsulta.listarJTable();
       
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jtRgIeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtRgIeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtRgIeActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        // TODO add your handling code here:
        
        // Exibe mensagem de confirmação de cancelamento //
  Object[] options = { "Sim", "Não" };
		int i = JOptionPane.showOptionDialog(null,
				"Deseja realmente cancelar o cadastro? Você perderá todos os dados!", "AVISO:",
				JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE, null,
				options, options[0]);
		if (i == JOptionPane.YES_OPTION) {
			this.dispose();
		}
    }//GEN-LAST:event_jbCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CadastroCliente().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(CadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JLabel jlBairro;
    private javax.swing.JLabel jlBairro1;
    private javax.swing.JLabel jlCEP;
    private javax.swing.JLabel jlCEP1;
    private javax.swing.JLabel jlCPF;
    private javax.swing.JLabel jlCel;
    private javax.swing.JLabel jlCidade;
    private javax.swing.JLabel jlCidade1;
    private javax.swing.JLabel jlCodCliente;
    private javax.swing.JLabel jlDataNasc;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlEndCobranca;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlNro;
    private javax.swing.JLabel jlNro1;
    private javax.swing.JLabel jlNro2;
    private javax.swing.JLabel jlObs;
    private javax.swing.JLabel jlRua;
    private javax.swing.JLabel jlRua1;
    private javax.swing.JLabel jlTel;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JLabel jlUF;
    private javax.swing.JLabel jlUF1;
    private javax.swing.JLabel jltipo;
    public javax.swing.JTextField jtBairro;
    public javax.swing.JTextField jtBairroCliente;
    public javax.swing.JFormattedTextField jtCel;
    public javax.swing.JFormattedTextField jtCep;
    public javax.swing.JFormattedTextField jtCepCliente;
    public javax.swing.JComboBox jtCidade;
    public javax.swing.JComboBox jtCidadeCliente;
    public javax.swing.JTextField jtCodCliente;
    public javax.swing.JFormattedTextField jtCpfCnpj;
    public javax.swing.JFormattedTextField jtDataNasc;
    public javax.swing.JTextField jtEmail;
    public javax.swing.JTextField jtNome;
    public javax.swing.JTextField jtNro;
    public javax.swing.JTextField jtNroCliente;
    public javax.swing.JTextField jtRgIe;
    public javax.swing.JTextField jtRua;
    public javax.swing.JTextField jtRuaCliente;
    public javax.swing.JFormattedTextField jtTel;
    public javax.swing.JComboBox jtUF;
    public javax.swing.JComboBox jtUFCliente;
    public javax.swing.JComboBox<String> tipo_cliente;
    public javax.swing.JTextArea txtObs;
    // End of variables declaration//GEN-END:variables


    public void getLastId(){
        ClienteDAO cliente = new ClienteDAO();
        int rs = cliente.getLastId();
        rs = rs + 1;
 
                
        jtCodCliente.setText(Integer.toString(rs));
    
    }

     // ENDEREÇO 1
       public void populateUF() throws SQLException{
       ClienteDAO uf = new ClienteDAO();
       ResultSet rs = uf.toComboBox();
       
        while(rs.next()){                   
            jtUFCliente.addItem(new Item(rs.getInt("id"), rs.getString("uf")));
        }
        
        jtUFCliente.addActionListener (new ActionListener () {
        public void actionPerformed(ActionEvent e) {
            int valor = (jtUFCliente.getSelectedIndex() + 1);
            try {
                populateCidade(valor);
            } catch (SQLException ex) {
                Logger.getLogger(CadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
});
    }
       
      public void populateCidade(int idCidade) throws SQLException{
       ClienteDAO cidade = new ClienteDAO();
       ResultSet rs = cidade.toComboBoxCidade(idCidade);
       jtCidadeCliente.removeAllItems();
        while(rs.next()){              
            jtCidadeCliente.addItem(new Item(rs.getInt("id"), rs.getString("nome")));
        }
    } 
       
    //ENDEREÇO 2
       public void populateUF2() throws SQLException{
       ClienteDAO uf = new ClienteDAO();
       ResultSet rs = uf.toComboBox();
       
        while(rs.next()){                   
            jtUF.addItem(new Item(rs.getInt("id"), rs.getString("uf")));
        }
        
        
        jtUF.addActionListener ((ActionEvent e) -> {
            int valor = (jtUF.getSelectedIndex() + 1);
            try {
                populateCidade2(valor);
            } catch (SQLException ex) {
                Logger.getLogger(CadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
       });
    }
    

    //Cidade 2 
    public void populateCidade2(int idCidade) throws SQLException{
       ClienteDAO cidade = new ClienteDAO();
       ResultSet rs = cidade.toComboBoxCidade(idCidade);
       jtCidade.removeAllItems();
        while(rs.next()){                   
            jtCidade.addItem(new Item(rs.getInt("id"), rs.getString("nome")));
        }
    } 
    
    

       
       
}
