/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ProdutoDAO;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Produto;

/**
 *
 * @author Pereira
 */
public class jfLancaProduto extends javax.swing.JFrame {
    
    PDV pdv;
   
    public jfLancaProduto(PDV pdv) {
        this.pdv = pdv;
        
        initComponents();
        
        Color backgroundColor = new Color(206, 222, 255);
        // Alterar a cor do formulário: //
       this.getContentPane().setBackground(backgroundColor);
       
       
        DefaultTableModel modelo = new DefaultTableModel();
        modelo = (DefaultTableModel) jtableProduto.getModel();
        jtableProduto.setRowSorter(new TableRowSorter(modelo));
        
        listarJTable();
        }

    jfLancaProduto() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public void listarJTable(){
        
            DefaultTableModel modelo = new DefaultTableModel();
            modelo = (DefaultTableModel) jtableProduto.getModel();
            modelo.setNumRows(0);
            
            ProdutoDAO produtoDAO = new ProdutoDAO();
            
            for(Produto prod: produtoDAO.listarProduto()){
                
                modelo.addRow(new Object[]{
                
                 prod.getIdProduto(),
                 prod.getCodEan(),
                 prod.getDiscriminacao(),
                 prod.getValorCusto(),
                 prod.getMargemLucro(),
                 prod.getCodMarca(),
                 prod.getCodCategoria()
                        
            });
            }   
        
    }
     public void listarJTableID(String disc){
        
            DefaultTableModel modelo = new DefaultTableModel();
            modelo = (DefaultTableModel) jtableProduto.getModel();
            modelo.setNumRows(0);
            
            ProdutoDAO produto = new ProdutoDAO();
            
            for(Produto prod: produto.listarProdutoID(disc)){
                
                modelo.addRow(new Object[]{
                
                    prod.getIdProduto(),
                    prod.getCodEan(),
                    prod.getDiscriminacao(),
                    prod.getValorCusto(),
                    prod.getMargemLucro(),
                    prod.getCodMarca(),
                    prod.getCodCategoria()
                        
                });
            }   
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtableProduto = new javax.swing.JTable();
        jbInserir = new javax.swing.JButton();
        jbAtualizar = new javax.swing.JButton();
        jtBusca = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtQuantidade = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta Produtos");

        jtableProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtableProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "EAN", "Discriminação", "Valor Custo", "Margem Lucro", "Código Marca", "Código Categoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtableProduto.setSelectionBackground(new java.awt.Color(102, 153, 255));
        jtableProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableProdutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtableProduto);
        if (jtableProduto.getColumnModel().getColumnCount() > 0) {
            jtableProduto.getColumnModel().getColumn(0).setResizable(false);
            jtableProduto.getColumnModel().getColumn(1).setResizable(false);
            jtableProduto.getColumnModel().getColumn(2).setResizable(false);
            jtableProduto.getColumnModel().getColumn(3).setResizable(false);
            jtableProduto.getColumnModel().getColumn(4).setResizable(false);
            jtableProduto.getColumnModel().getColumn(5).setResizable(false);
            jtableProduto.getColumnModel().getColumn(6).setResizable(false);
        }

        jbInserir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus-black-symbol.png"))); // NOI18N
        jbInserir.setText("Inserir");
        jbInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInserirActionPerformed(evt);
            }
        });

        jbAtualizar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh-page-option.png"))); // NOI18N
        jbAtualizar.setText("Atualizar");
        jbAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtualizarActionPerformed(evt);
            }
        });

        jbBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("Quantidade: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbBuscar)
                        .addContainerGap(473, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbInserir)
                        .addGap(18, 18, 18)
                        .addComponent(jbAtualizar)
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbInserir)
                    .addComponent(jbAtualizar)
                    .addComponent(jLabel1)
                    .addComponent(jtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        setSize(new java.awt.Dimension(804, 493));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtualizarActionPerformed
     //   listarJTable();
    }//GEN-LAST:event_jbAtualizarActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
       listarJTableID(jtBusca.getText());
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jtableProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableProdutoMouseClicked
            
        if(evt.getClickCount() == 2){
            
            try {
                CadastroProduto cadProd = new CadastroProduto();
                cadProd.setVisible(true);
                cadProd.op = "editar";
                int indiceLinha = jtableProduto.getSelectedRow();
                cadProd.jtIdProduto.setEnabled(false);
                cadProd.jtIdProduto.setText(jtableProduto.getValueAt(indiceLinha, 0).toString());
                cadProd.jtCodEan.setText(jtableProduto.getValueAt(indiceLinha, 1).toString());
                cadProd.jtDiscriminacao.setText(jtableProduto.getValueAt(indiceLinha, 2).toString());
                cadProd.jtValorCusto.setText(jtableProduto.getValueAt(indiceLinha, 3).toString());
                cadProd.jtMargemLucro.setText(jtableProduto.getValueAt(indiceLinha, 4).toString());
                cadProd.jtValorUN.setText(jtableProduto.getValueAt(indiceLinha, 5).toString());
                cadProd.comboMarca.setSelectedItem(jtableProduto.getValueAt(indiceLinha, 6).toString());
                cadProd.comboCategoria.setSelectedItem(jtableProduto.getValueAt(indiceLinha, 7).toString());

                
            } catch (SQLException ex) {
                Logger.getLogger(jfLancaProduto.class.getName()).log(Level.SEVERE, null, ex);
            }   
        }
    }//GEN-LAST:event_jtableProdutoMouseClicked

    private void jbInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInserirActionPerformed
        if(jtQuantidade.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Digite a quantidade!");
        }
        else{

            Produto p;
            int indiceLinha = jtableProduto.getSelectedRow();

            p = new Produto(
                    Integer.parseInt(jtableProduto.getValueAt(indiceLinha, 0).toString()),
                    jtableProduto.getValueAt(indiceLinha, 1).toString(),
                    jtableProduto.getValueAt(indiceLinha, 2).toString(),
                    Float.parseFloat(jtableProduto.getValueAt(indiceLinha, 3).toString()),
                    Float.parseFloat(jtableProduto.getValueAt(indiceLinha, 4).toString()),
                    Integer.parseInt(jtableProduto.getValueAt(indiceLinha, 5).toString()),
                    Integer.parseInt(jtableProduto.getValueAt(indiceLinha, 6).toString())
            );

            p.setQuantidade(Integer.parseInt(jtQuantidade.getText()));

            this.pdv.lancarProduto(p);
        }
    }//GEN-LAST:event_jbInserirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfLancaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfLancaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfLancaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfLancaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfLancaProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAtualizar;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbInserir;
    private javax.swing.JTextField jtBusca;
    private javax.swing.JTextField jtQuantidade;
    private javax.swing.JTable jtableProduto;
    // End of variables declaration//GEN-END:variables
}
