/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author al1610597
 */
public class jfTelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form jfTelaPrincipal
     */
    public jfTelaPrincipal() {
        initComponents();
        
    /* Bloqueia o Resize: 
        this.setResizable(false); */
        
    // Maximiza a janela ao iniciar: 
        this.setExtendedState(jfTelaPrincipal.MAXIMIZED_BOTH); //
      
     
        Color backgroundColor = new Color(179, 206, 230);
        // Alterar a cor do formulário: //
       this.getContentPane().setBackground(backgroundColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jmCadastro = new javax.swing.JMenu();
        jmProdutos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmCategorias = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jmMarcas = new javax.swing.JMenuItem();
        jsClienteFornecedor = new javax.swing.JPopupMenu.Separator();
        jmClientes = new javax.swing.JMenuItem();
        jsFornecedorUsuario = new javax.swing.JPopupMenu.Separator();
        jmFornecedor = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jmUsuarios = new javax.swing.JMenuItem();
        jmConsultas = new javax.swing.JMenu();
        jmConsultaProduto = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jmConsultaCategoria = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jmConsultaMarca = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jmConsultaCliente = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jmConsultaFornecedor = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jmConsultaUsuario = new javax.swing.JMenuItem();
        jmVendas = new javax.swing.JMenu();
        jmNovaVenda = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jmRelatorios = new javax.swing.JMenuItem();
        jmSuporte = new javax.swing.JMenu();
        jmSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA DE GESTÃO PARA PERFUMARIAS");

        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jmCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus-black-symbol.png"))); // NOI18N
        jmCadastro.setText("Cadastros");
        jmCadastro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jmProdutos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barcode.png"))); // NOI18N
        jmProdutos.setText("Produtos");
        jmProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmProdutosActionPerformed(evt);
            }
        });
        jmCadastro.add(jmProdutos);
        jmCadastro.add(jSeparator1);

        jmCategorias.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tag-black-shape.png"))); // NOI18N
        jmCategorias.setText("Categorias");
        jmCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCategoriasActionPerformed(evt);
            }
        });
        jmCadastro.add(jmCategorias);
        jmCadastro.add(jSeparator3);

        jmMarcas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmMarcas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ticket.png"))); // NOI18N
        jmMarcas.setText("Marcas");
        jmMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMarcasActionPerformed(evt);
            }
        });
        jmCadastro.add(jmMarcas);
        jmCadastro.add(jsClienteFornecedor);

        jmClientes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/group-profile-users.png"))); // NOI18N
        jmClientes.setText("Clientes");
        jmClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmClientesActionPerformed(evt);
            }
        });
        jmCadastro.add(jmClientes);
        jmCadastro.add(jsFornecedorUsuario);

        jmFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delivery-truck-silhouette.png"))); // NOI18N
        jmFornecedor.setText("Fornecedores");
        jmFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFornecedorActionPerformed(evt);
            }
        });
        jmCadastro.add(jmFornecedor);
        jmCadastro.add(jSeparator2);

        jmUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user-shape.png"))); // NOI18N
        jmUsuarios.setText("Usuários");
        jmUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmUsuariosActionPerformed(evt);
            }
        });
        jmCadastro.add(jmUsuarios);

        jMenuBar1.add(jmCadastro);

        jmConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        jmConsultas.setText("Consultas");
        jmConsultas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jmConsultaProduto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmConsultaProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barcode.png"))); // NOI18N
        jmConsultaProduto.setText("Produtos");
        jmConsultaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmConsultaProdutoActionPerformed(evt);
            }
        });
        jmConsultas.add(jmConsultaProduto);
        jmConsultas.add(jSeparator5);

        jmConsultaCategoria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmConsultaCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tag-black-shape.png"))); // NOI18N
        jmConsultaCategoria.setText("Categorias");
        jmConsultaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmConsultaCategoriaActionPerformed(evt);
            }
        });
        jmConsultas.add(jmConsultaCategoria);
        jmConsultas.add(jSeparator6);

        jmConsultaMarca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmConsultaMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ticket.png"))); // NOI18N
        jmConsultaMarca.setText("Marcas");
        jmConsultaMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmConsultaMarcaActionPerformed(evt);
            }
        });
        jmConsultas.add(jmConsultaMarca);
        jmConsultas.add(jSeparator7);

        jmConsultaCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmConsultaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/group-profile-users.png"))); // NOI18N
        jmConsultaCliente.setText("Clientes");
        jmConsultaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmConsultaClienteActionPerformed(evt);
            }
        });
        jmConsultas.add(jmConsultaCliente);
        jmConsultas.add(jSeparator8);

        jmConsultaFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmConsultaFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delivery-truck-silhouette.png"))); // NOI18N
        jmConsultaFornecedor.setText("Fornecedores");
        jmConsultaFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmConsultaFornecedorActionPerformed(evt);
            }
        });
        jmConsultas.add(jmConsultaFornecedor);
        jmConsultas.add(jSeparator9);

        jmConsultaUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmConsultaUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user-shape.png"))); // NOI18N
        jmConsultaUsuario.setText("Usuários");
        jmConsultaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmConsultaUsuarioActionPerformed(evt);
            }
        });
        jmConsultas.add(jmConsultaUsuario);

        jMenuBar1.add(jmConsultas);

        jmVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/credit-card.png"))); // NOI18N
        jmVendas.setText("Vendas");
        jmVendas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jmNovaVenda.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmNovaVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/shopping-cart-black-shape.png"))); // NOI18N
        jmNovaVenda.setText("Iniciar Venda");
        jmNovaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmNovaVendaActionPerformed(evt);
            }
        });
        jmVendas.add(jmNovaVenda);
        jmVendas.add(jSeparator4);

        jmRelatorios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/calendar-page-empty.png"))); // NOI18N
        jmRelatorios.setText("Visualizar Vendas");
        jmVendas.add(jmRelatorios);

        jMenuBar1.add(jmVendas);

        jmSuporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cog-wheel-silhouette.png"))); // NOI18N
        jmSuporte.setText("Suporte");
        jmSuporte.setToolTipText("");
        jmSuporte.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuBar1.add(jmSuporte);

        jmSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sign-out-option.png"))); // NOI18N
        jmSair.setText("Sair");
        jmSair.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmSairMouseClicked(evt);
            }
        });
        jmSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSairActionPerformed(evt);
            }
        });
        jMenuBar1.add(jmSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1066, 780));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFornecedorActionPerformed
        // TODO add your handling code here:
        CadastroFornecedor tela = null;
        try {
            tela = new CadastroFornecedor();
        } catch (SQLException ex) {
            Logger.getLogger(jfTelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        tela.setVisible(true);
        //jfTelaPrincipal.this.dispose();  
    }//GEN-LAST:event_jmFornecedorActionPerformed

    private void jmUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmUsuariosActionPerformed
     // TODO add your handling code here: 
        jfCadastroUsuario tela;
        try {
            tela = new jfCadastroUsuario();
            tela.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(jfTelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        //jfTelaPrincipal.this.dispose();     
        
    }//GEN-LAST:event_jmUsuariosActionPerformed

    private void jmCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCategoriasActionPerformed
        // TODO add your handling code here:
        CadastroCategoria tela = new CadastroCategoria();
        tela.setVisible(true);
        //jfTelaPrincipal.this.dispose();     
    }//GEN-LAST:event_jmCategoriasActionPerformed

    private void jmClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmClientesActionPerformed
        // TODO add your handling code here:
        CadastroCliente tela = null;
        try {
            tela = new CadastroCliente();
        } catch (SQLException ex) {
            Logger.getLogger(jfTelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        tela.setVisible(true);
    }//GEN-LAST:event_jmClientesActionPerformed

    private void jmProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmProdutosActionPerformed
        // TODO add your handling code here:
       CadastroProduto tela = null;
        try {
            tela = new CadastroProduto();
        } catch (SQLException ex) {
            Logger.getLogger(jfTelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        tela.setVisible(true);
        //jfTelaPrincipal.this.dispose();     
    }//GEN-LAST:event_jmProdutosActionPerformed

    private void jmMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMarcasActionPerformed
        // TODO add your handling code here:
        CadastroMarca tela = new CadastroMarca();
        tela.setVisible(true);
        //jfTelaPrincipal.this.dispose();  
    }//GEN-LAST:event_jmMarcasActionPerformed

    private void jmNovaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmNovaVendaActionPerformed
        // TODO add your handling code here:
        PDV tela = new PDV();
        tela.setVisible(true);
    }//GEN-LAST:event_jmNovaVendaActionPerformed

    private void jmSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSairActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jmSairActionPerformed

    private void jmSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmSairMouseClicked
          // TODO add your handling code here:
           // Exibe mensagem de confirmação de cancelamento //
  Object[] options = { "Sim", "Não" };
		int i = JOptionPane.showOptionDialog(null,
				"Deseja realmente sair do sistema?", "AVISO:",
				JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE, null,
				options, options[0]);
		if (i == JOptionPane.YES_OPTION) {
			System.exit(0);
		}  
    }//GEN-LAST:event_jmSairMouseClicked

    private void jmConsultaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmConsultaProdutoActionPerformed
       jfConsultaProduto tela = new jfConsultaProduto();
       tela.setVisible(true);
    }//GEN-LAST:event_jmConsultaProdutoActionPerformed

    private void jmConsultaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmConsultaCategoriaActionPerformed
       jfConsultaCategoria tela = new jfConsultaCategoria();
       tela.setVisible(true);
    }//GEN-LAST:event_jmConsultaCategoriaActionPerformed

    private void jmConsultaMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmConsultaMarcaActionPerformed
       jfConsultaMarca tela = new jfConsultaMarca();
       tela.setVisible(true);
    }//GEN-LAST:event_jmConsultaMarcaActionPerformed

    private void jmConsultaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmConsultaClienteActionPerformed
       jfConsultaCliente tela = new jfConsultaCliente();
       tela.setVisible(true);
    }//GEN-LAST:event_jmConsultaClienteActionPerformed

    private void jmConsultaFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmConsultaFornecedorActionPerformed
       jfConsultaFornecedor tela = new jfConsultaFornecedor();
       tela.setVisible(true);
    }//GEN-LAST:event_jmConsultaFornecedorActionPerformed

    private void jmConsultaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmConsultaUsuarioActionPerformed
       jfConsultaUsuario tela = new jfConsultaUsuario();
       tela.setVisible(true);
    }//GEN-LAST:event_jmConsultaUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfTelaPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JMenu jmCadastro;
    private javax.swing.JMenuItem jmCategorias;
    private javax.swing.JMenuItem jmClientes;
    private javax.swing.JMenuItem jmConsultaCategoria;
    private javax.swing.JMenuItem jmConsultaCliente;
    private javax.swing.JMenuItem jmConsultaFornecedor;
    private javax.swing.JMenuItem jmConsultaMarca;
    private javax.swing.JMenuItem jmConsultaProduto;
    private javax.swing.JMenuItem jmConsultaUsuario;
    private javax.swing.JMenu jmConsultas;
    private javax.swing.JMenuItem jmFornecedor;
    private javax.swing.JMenuItem jmMarcas;
    private javax.swing.JMenuItem jmNovaVenda;
    private javax.swing.JMenuItem jmProdutos;
    private javax.swing.JMenuItem jmRelatorios;
    private javax.swing.JMenu jmSair;
    private javax.swing.JMenu jmSuporte;
    private javax.swing.JMenuItem jmUsuarios;
    private javax.swing.JMenu jmVendas;
    private javax.swing.JPopupMenu.Separator jsClienteFornecedor;
    private javax.swing.JPopupMenu.Separator jsFornecedorUsuario;
    // End of variables declaration//GEN-END:variables
}
